version: "3.5"
services:
  validator-ejector:
    build:
      context: validator-ejector
      args:
        VALIDATOR_EJECTOR_VERSION: 1.5.0
        NETWORK: holesky
    environment:
      OPERATOR_ID: ""
      CHARON_TO_EXIT_NUMBER: 1
    restart: on-failure
    volumes:
      - validator-ejector:/exitmessages
    image: validator-ejector.obol-lido-ejector-holesky.dnp.dappnode.eth:0.1.0
  lido-dv-exit:
    build:
      context: lido-dv-exit
      args:
        LIDO_DV_EXIT_VERSION: e8bee1f
        NETWORK: holesky
    environment:
      LOG_LEVEL: info
      VALIDATOR_QUERY_CHUNK_SIZE: 5
      CHARON_TO_EXIT_NUMBER: 1
    restart: on-failure
    volumes:
      - validator-ejector:/exitmessages
      - charon-data:/charon
    image: lido-dv-exit.obol-lido-ejector-holesky.dnp.dappnode.eth:0.1.0
volumes:
  validator-ejector: {}
  charon-data: {}
